version: '3'

services:
  ssh:
    build:
      dockerfile: ssh-dockerfile
      context: .
    ports:
      - "20022:22"
    networks:
      - private
      - public
  webgoatlocal:
    image: webgoat/webgoat-8.0
    networks:
      - private
  metasploit:
    build: 
      dockerfile: metasploit-dockerfile
      context: .
    networks:
      - public
    ports:
      - "9990-9999:9990-9999"
    entrypoint: tail -f /dev/null

networks:
  private:
  public: